//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrowing
    {
        public long Id { get; set; }
        public System.DateTime DateOfBorrowing { get; set; }
        public long UserId { get; set; }
        public long BookId { get; set; }
        public System.DateTime Deadline { get; set; }
        public bool IsPenalty { get; set; }
        public int TotalPenalty { get; set; }
    }
}
